spring.application.name=Infp_practice

gemini.api.key=AQ.Ab8RN6LuX109BHNfZ8cVREeNNKQuNZsUvj3z1G0dBoFKry52TQ

# 한글 입출력 설정 (한글 깨짐 방지)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JPA 연동 (DB 연결)
# hibernate: SQL문 자동 생성
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

# 프로젝트가 DB접속에 필요한 정보들 입력

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver